# Generated by Django 2.2.3 on 2019-10-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='selectedfields',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
