# Generated by Django 2.2.3 on 2019-10-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20191027_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='availablecat',
            field=models.CharField(default=21, max_length=100),
            preserve_default=False,
        ),
    ]
