# Generated by Django 2.2.3 on 2019-10-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_auto_20191027_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cat',
        ),
    ]
